version: '3'

services:
  database:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    volumes:
      - ./mysql:/var/lib/mysql

  greenpiece:
    build: .
    entrypoint: /app/entrypoint
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - database
    env_file:
      - env.development
    volumes:
      - .:/app

volumes:
  app:
  mysql:
