services:
  #########
  # MYSQL #
  #########
  mysql:
    image: mysql:8.0.28
    env_file: .env  
    ports:
      - "3306:3306"
    volumes:
      - mysql:/var/lib/mysql
  ######
  # GP #
  ######
  server:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mysql
    ports: 
      - "3000:3000"
    volumes:
      - .:/greenpiece
    env_file: .env
    links:
      - "mysql"
  #########
  # REDIS #
  #########
  redis:
    image: redis:6.2.6-alpine
    volumes:
      - redis:/data
  ###########
  # SIDEKIQ #
  ###########
  sidekiq:
    build:
      context: .
      dockerfile: Dockerfile
    command: bundle exec sidekiq --environment development -C config/sidekiq.yml 
    depends_on:
      - redis
    ports: []
volumes:
  greenpiece:
  mysql:
  redis: