services:
  #########
  # MYSQL #
  #########
  mysql:
    container_name: mysql
    image: mysql:8.0.28
    ports:
      - "3306:3306"
    volumes:
      - mysql:/var/lib/mysql
    env_file: .env
  #########
  # REDIS #
  #########
  redis:
    container_name: redis
    image: redis:6.2.6-alpine
    env_file: .env
  ###########
  # SIDEKIQ #
  ###########
  sidekiq:
    container_name: sidekiq
    build: .
    depends_on:
      - mysql
      - redis
    command: bundle exec sidekiq -C config/sidekiq.yml
    volumes:
      - .:/greenpiece
    env_file:
      - .env
  ######
  # GP #
  ######
  server:
    container_name: server
    tty: true
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    depends_on:
      - mysql
      - sidekiq
    volumes:
      - .:/greenpiece
    ports:
      - "3000:3000"
    env_file:
      - .env
  server_test:
    container_name: server-test
    tty: true
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile
    command: bundle exec rails s -p 3001 -b '0.0.0.0' -P tmp/pids/server-test.pid
    depends_on:
      - mysql
      - sidekiq
    volumes:
      - .:/greenpiece
    ports:
      - "3001:3001"
    env_file:
      - .envtest
###########
# VOLUMES #
###########
volumes:
  greenpiece:
  mysql: