services:
  #########
  # MYSQL #
  #########
  mysql:
    image: mysql:8.0.28
    ports:
      - "3306:3306"
    volumes:
      - mysql:/var/lib/mysql
    env_file: .env
  #########
  # REDIS #
  #########
  redis:
    image: redis:6.2.6-alpine
    env_file: .env
  ###########
  # SIDEKIQ #
  ###########
  sidekiq:
    build: .
    depends_on:
      - mysql
      - redis
    command: bundle exec sidekiq -C config/sidekiq.yml
    volumes:
      - .:/greenpiece
    env_file:
      - .env
  ######
  # GP #
  ######
  server:
    build:
      context: .
      dockerfile: Dockerfile
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    depends_on:
      - mysql
      - sidekiq
    volumes:
      - .:/greenpiece
    ports:
      - "3000:3000"
    env_file:
      - .env
###########
# VOLUMES #
###########
volumes:
  greenpiece:
  mysql: