services:
  #########
  # MYSQL #
  #########
  mysql:
    image: mysql:8.0.28
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: greenpiece_dev
    ports:
      - "3306:3306"
    volumes:
      - mysql:/var/lib/mysql
  ######
  # GP #
  ######
  server:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mysql
    ports: 
      - "3000:3000"
    volumes:
      - .:/greenpiece
      - bundle:/bundle
    env_file: .env
    links:
      - "mysql"
    environment:
      - RAILS_ENV=development
  #########
  # REDIS #
  #########
  redis:
    image: redis:6.2.6-alpine
    volumes:
      - redis:/data
  ###########
  # SIDEKIQ #
  ###########
  sidekiq:
    build:
      context: .
      dockerfile: Dockerfile
    command: bundle exec sidekiq
    depends_on:
      - redis
    ports: []
volumes:
  mysql:
  redis:
  bundle: