default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: root
  host: 127.0.0.1

development:
  <<: *default
  database: <%= ENV["DB_NAME"] %>-development

test:
  <<: *default
  database: <%= ENV["DB_NAME"] %>-test

production:
  <<: *default
  database: <%= ENV["DB_NAME"] %>-production
  username: <%= ENV["DB_USERNAME"] %>
  password: <%= ENV["DB_PASSWORD"] %>
